routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
  if (auth::user()) {
    return view('admin.dashboard');
  }
    return view('auth.login');
});

Auth::routes();

Route::group([
    'prefix' => 'admin',
    'middleware' => 'auth'],
  function(){
    Route::view('inicio', 'admin.dashboard')->name('admin.dashboard');
    Route::resource('users', 'UserController');
    Route::resource('cars', 'CarController');

    Route::post('saveDataAccess', 'SaveDataAccessController@saveDataAccess')->name('save.data');
});

app/Car.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Car extends Model
{
    protected $fillable = [
        'car_brand',
        'car_model',
        'car_plate',
        'car_seats',
        'user_id',
    ];

    // Mutators

        // Setters

        // Getters

    // Relarionships

    public function User()
    {
       return $this->belongsTo(User::class);
    }

    // Methods
}

app/Http/Controllers/Api/CarController.php
<?php

namespace App\Http\Controllers\Api;

use App\Car;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CarController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return datatables()
                ->eloquent(Car::query())                
                ->addColumn('action', 'admin.cars.partials.actions')
                ->rawColumns(['action'])
                ->toJson();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Car  $car
     * @return \Illuminate\Http\Response
     */
    public function show(Car $car)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Car  $car
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Car $car)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Car  $car
     * @return \Illuminate\Http\Response
     */
    public function destroy(Car $car)
    {
        //
    }
}

app/Http/Controllers/CarController.php
<?php

namespace App\Http\Controllers;

use App\Car;
use App\User;
use Illuminate\Http\Request;
use App\Http\Requests\CarRequest;
use App\Http\Requests\CarUpdateRequest;

class CarController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {    
        return view('admin.cars.index');        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // $users = User::all();
        // return view('admin.cars.create', compact('users'));

        $users = User::all();

        $response = [
            'users' => $users,
            'code' => 200
        ];

        return $response;
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CarRequest $request)
    {    
        // $car = Car::create($request->all());

        // return redirect()->route('cars.index')->with('info', 'El carro ha sido creado exitosamente');

        $car = Car::create($request->all());

        $response = [
            'success'   => 'Se ha creado un carro exitosamente',
            'codigo'  => '200',
            'car' => $car
        ];

        return $response;
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Car  $car
     * @return \Illuminate\Http\Response
     */
    public function show(Car $car)
    {
        // return view('admin.cars.show', compact('car'));

        $response = [
            'car' => $car,
            'car_user_relation' => $car->User,
            'code' => 200,
        ];

        return $response;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Car  $car
     * @return \Illuminate\Http\Response
     */
    public function edit(Car $car)
    {        
        $users = User::where('id', '!=', $car->user_id)->get();

        // dd($users);
        // return view('admin.cars.edit', compact('car', 'users'));

        $response = [
            'users' => $users,
            'car' => $car,
            'relation' => $car->User,
            'code' => 200
        ];

        return $response;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Car  $car
     * @return \Illuminate\Http\Response
     */
    public function update(CarUpdateRequest $request, Car $car)
    {
        $car = $car->update($request->all());        

        // return redirect()->route('cars.index')->with('info', 'Se ha actualizado el carro exitosamente');

        $response = [
            'success'   => 'Se ha actualizado el carro exitosamente',
            'codigo'  => '200',
            'user' => $car
        ];

        return $response;

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Car  $car
     * @return \Illuminate\Http\Response
     */
    public function destroy(Car $car)
    {
        
        $car->delete();

        // return redirect()->back()->with('info', 'Se ha eliminado el carro exitosamente');

        $response = [
            'success' => 'Se ha eliminado el carro exitosamente',
            'code' => 200            
        ];

        return $response;
    }
}

resources/views/admin/cars/create.blade.php
@extends('layouts.admin')

@push('custom-styles')
    <!-- SweetAlert2 -->
    <link rel="stylesheet" href="/adminlte/plugins/sweetalert2/sweetalert2.min.css">
    <!-- Select2 -->
    <link rel="stylesheet" href="/adminlte/plugins/select2/css/select2.min.css">
    <style>
        .has-error .select2-selection {
            border: 1px solid #dc3545;
            border-radius: 4px;
            border-color:rgb(185, 74, 72) !important;
        }
    </style>
@endpush

@section('header')
    <div class="col-sm-6">
        <h1 class="m-0 text-dark">Módulo Carros</h1>
    </div><!-- /.col -->
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}"><i class="nav-icon fas fa-tachometer-alt"></i> Admin</a></li>
        <li class="breadcrumb-item"><a href="{{ route('cars.index') }}"><i class=" fas fa-car"></i> Mod - Carros</a></li>
        <li class="breadcrumb-item active">Crear Carro</li>
        </ol>
    </div><!-- /.col -->
@endsection

@section('content')
    <div class="col-md-12">
        <section class="content">
            <!-- Default box -->
            <div class="card card-success card-outline">
            <div class="card-header">
                <h3 class="card-title float-left">Creación de carros</h3>

                <a href="{{ route('cars.index') }}" class="btn btn-outline-secondary float-right">Regresar <i class="fas fa-arrow-alt-circle-left"></i></a>                
            </div>
            <div class="card-body">
                <form action="{{ route('cars.store') }}" method="post">
                    @include('admin.cars.partials.createForm')
                </form>                
            </div>
            <!-- /.card-body -->
            {{-- <div class="card-footer">            
                
            </div> --}}
            <!-- /.card-footer-->
            </div>
            <!-- /.card -->  
        </section>
        <!-- /.content -->
    </div>
@endsection

@push('custom-scripts')
    <!-- SweetAlert2 -->
    <script src="/adminlte/plugins/sweetalert2/sweetalert2.min.js"></script>    
    @include('admin.partials.sweetAlert.error')
    <!-- Select2 -->
    <script src="/adminlte/plugins/select2/js/select2.full.min.js"></script>

    <script>
        $(function () {
            //Initialize Select2 Elements
            $('.select2-users').select2()
        })
    </script>
@endpush

resources/views/admin/cars/edit.blade.php
@extends('layouts.admin')

@push('custom-styles')
    <!-- SweetAlert2 -->
    <link rel="stylesheet" href="/adminlte/plugins/sweetalert2/sweetalert2.min.css">
    <!-- Select2 -->
    <link rel="stylesheet" href="/adminlte/plugins/select2/css/select2.min.css">
    <style>
        .has-error .select2-selection {
            border: 1px solid #dc3545;
            border-radius: 4px;
            border-color:rgb(185, 74, 72) !important;
        }
    </style>
@endpush

@section('header')
    <div class="col-sm-6">
        <h1 class="m-0 text-dark">Módulo Carros</h1>
    </div><!-- /.col -->
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}"><i class="nav-icon fas fa-tachometer-alt"></i> Admin</a></li>
        <li class="breadcrumb-item"><a href="{{ route('cars.index') }}"><i class=" fas fa-car"></i> Mod - Carros</a></li>
        <li class="breadcrumb-item active">Editar carro - {{ $car->id }}</li>
        </ol>
    </div><!-- /.col -->
@endsection

@section('content')
    <div class="col-md-12">
        <section class="content">
            <!-- Default box -->
            <div class="card card-warning card-outline">
            <div class="card-header">
                <h3 class="card-title float-left">Edición de carro</h3>

                <a href="{{ route('cars.index') }}" class="btn btn-outline-secondary float-right">Regresar <i class="fas fa-arrow-alt-circle-left"></i></a>                
            </div>
            <div class="card-body">
                <form action="{{ route('cars.update', $car) }}" method="post">
                    @include('admin.cars.partials.editForm')
                </form>                
            </div>
            <!-- /.card-body -->
            {{-- <div class="card-footer">            
                
            </div> --}}
            <!-- /.card-footer-->
            </div>
            <!-- /.card -->  
        </section>
        <!-- /.content -->
    </div>
@endsection

@push('custom-scripts')
    <!-- SweetAlert2 -->
    <script src="/adminlte/plugins/sweetalert2/sweetalert2.min.js"></script>
    @include('admin.partials.sweetAlert.error')
    <!-- Select2 -->
    <script src="/adminlte/plugins/select2/js/select2.full.min.js"></script>

    <script>
        $(function () {
            //Initialize Select2 Elements
            $('.select2-users').select2()
        })
    </script>
@endpush

resources/views/admin/cars/show.blade.php
@extends('layouts.admin')

@push('custom-styles')
    
@endpush

@section('header')
    <div class="col-sm-6">
        <h1 class="m-0 text-dark">Módulo Carrros</h1>
    </div><!-- /.col -->
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href=""><i class="nav-icon fas fa-tachometer-alt"></i> Admin</a></li>
        <li class="breadcrumb-item"><a href="{{ route('cars.index') }}"><i class=" fas fa-car"></i> Mod - Carros</a></li>
        <li class="breadcrumb-item active">Carro - {{ $car->name }}</li>
        </ol>
    </div><!-- /.col -->
@endsection

@section('content')
    <div class="col-md-12">
        <section class="content">
            <!-- Default box -->
            <div class="card card-primary card-outline">
            <div class="card-header">                
                <h3 class="card-title float-left">Visualización de carro - {{ $car->id }}</h3>                
                <a class="btn btn-outline-success float-right" href="{{ route('cars.edit', $car) }}">Editar carro <i class="fas fa-car"></i></a>
                    {{-- <button class="btn btn-success btn-outline" data-toggle="modal" data-target="#addBtn">Crear usuario <i class="fas fa-plus"></i></button> --}}
                    {{-- @include('admin.cars.partials.create_car_modal') --}}                    
            </div>
            
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <h3>Persona que conduce este carro:</h3>
                        <div class="col-md-11 offset-1">
                            <strong><a href="{{ route('users.show', $car->User->id) }}">{{ $car->User->name }}</a> - {{ $car->User->email }}</strong>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <h3>Marca del carro:</h3>
                        <div class="col-md-11 offset-1">
                            <strong>{{ $car->car_brand }}</strong>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <h3>Placa del carro:</h3>
                        <div class="col-md-11 offset-1">
                            <strong>{{ $car->car_plate }}</strong>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <h3>Modelo del carro:</h3>
                        <div class="col-md-11 offset-1">
                            <strong>{{ $car->car_model }}</strong>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <h3>Número de asientos del carro:</h3>
                        <div class="col-md-11 offset-1">
                            <strong>{{ $car->car_seats}}</strong>
                        </div>
                    </div>
                      
                </div>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">            
                <a href="{{ route('cars.index') }}" class="btn btn-outline-secondary float-right">Regresar <i class="fas fa-arrow-alt-circle-left"></i></a>
            </div>
            <!-- /.card-footer-->
            </div>
            <!-- /.card -->  
        </section>
        <!-- /.content -->
    </div>
    
@endsection

@push('custom-scripts')    

@endpush