routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
  if (auth::user()) {
    return view('admin.dashboard');
  }
    return view('auth.login');
});

Auth::routes();

Route::group([
    'prefix' => 'admin',
    'middleware' => 'auth'],
  function(){
    Route::view('inicio', 'admin.dashboard')->name('admin.dashboard');
    Route::resource('users', 'UserController');
    Route::resource('cars', 'CarController');

    Route::post('saveDataAccess', 'SaveDataAccessController@saveDataAccess')->name('save.data');
});

app/Car.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Car extends Model
{
    protected $fillable = [
        'car_brand',
        'car_model',
        'car_plate',
        'car_seats',
        'user_id',
    ];

    // Mutators

        // Setters

        // Getters

    // Relarionships

    public function User()
    {
       return $this->belongsTo(User::class);
    }

    // Methods
}

app/Http/Controllers/Api/CarController.php
<?php

namespace App\Http\Controllers\Api;

use App\Car;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CarController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return datatables()
                ->eloquent(Car::query())                
                ->addColumn('action', 'admin.cars.partials.actions')
                ->rawColumns(['action'])
                ->toJson();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Car  $car
     * @return \Illuminate\Http\Response
     */
    public function show(Car $car)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Car  $car
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Car $car)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Car  $car
     * @return \Illuminate\Http\Response
     */
    public function destroy(Car $car)
    {
        //
    }
}

app/Http/Controllers/CarController.php
<?php

namespace App\Http\Controllers;

use App\Car;
use App\User;
use Illuminate\Http\Request;
use App\Http\Requests\CarRequest;
use App\Http\Requests\CarUpdateRequest;

class CarController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {    
        return view('admin.cars.index');        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // $users = User::all();
        // return view('admin.cars.create', compact('users'));

        $users = User::all();

        $response = [
            'users' => $users,
            'code' => 200
        ];

        return $response;
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CarRequest $request)
    {    
        // $car = Car::create($request->all());

        // return redirect()->route('cars.index')->with('info', 'El carro ha sido creado exitosamente');

        $car = Car::create($request->all());

        $response = [
            'success'   => 'Se ha creado un carro exitosamente',
            'codigo'  => '200',
            'car' => $car
        ];

        return $response;
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Car  $car
     * @return \Illuminate\Http\Response
     */
    public function show(Car $car)
    {
        // return view('admin.cars.show', compact('car'));

        $response = [
            'car' => $car,
            'car_user_relation' => $car->User,
            'code' => 200,
        ];

        return $response;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Car  $car
     * @return \Illuminate\Http\Response
     */
    public function edit(Car $car)
    {        
        $users = User::where('id', '!=', $car->user_id)->get();

        // dd($users);
        // return view('admin.cars.edit', compact('car', 'users'));

        $response = [
            'users' => $users,
            'car' => $car,
            'relation' => $car->User,
            'code' => 200
        ];

        return $response;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Car  $car
     * @return \Illuminate\Http\Response
     */
    public function update(CarUpdateRequest $request, Car $car)
    {
        $car = $car->update($request->all());        

        // return redirect()->route('cars.index')->with('info', 'Se ha actualizado el carro exitosamente');

        $response = [
            'success'   => 'Se ha actualizado el carro exitosamente',
            'codigo'  => '200',
            'user' => $car
        ];

        return $response;

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Car  $car
     * @return \Illuminate\Http\Response
     */
    public function destroy(Car $car)
    {
        
        $car->delete();

        // return redirect()->back()->with('info', 'Se ha eliminado el carro exitosamente');

        $response = [
            'success' => 'Se ha eliminado el carro exitosamente',
            'code' => 200            
        ];

        return $response;
    }
}

resources/views/admin/cars/partials/actions.blade.php
<style>
    .my-button-info {
        margin: 5px;
        padding: 5px;
        /* height: 20px; */
        /* width: 20%; */
        border: solid 1px black;
    }
    a.my-button-info:hover {
        background: #17a2b8;
        color: #ffffff;
        text-decoration: none;
    }

    .my-button-warning {
        margin: 5px;
        padding: 5px;
        /* height: 20px; */
        /* width: 20%; */
        border: solid 1px black;
    }
    a.my-button-warning:hover {
        background: #ffc107;
        color: #ffffff;
        text-decoration: none;
    }

    .my-button-danger {
        margin: 5px;
        padding: 5px;
        /* height: 20px; */
        /* width: 20%; */
        border: solid 1px black;
    }
    a.my-button-danger:hover {
        background: #dc3545;
        color: #ffffff;
        text-decoration: none;
    }
</style>

<div class="btn-group float-right">                                            
    <a class="my-button-info viewCar" href="javascript:void(0)" data-id="{{ $id }}"><i class="fas fa-align-left fa-eye"></i></a>
    <a class="my-button-warning editCar" href="javascript:void(0)" data-id="{{ $id }}"><i class="fas fa-user-edit"></i></a>
    <a class="my-button-danger deleteCar" href="javascript:void(0)" data-id="{{ $id }}"><i class="fa fa-trash"></i></a> 
</div>

resources/views/admin/cars/partials/createForm.blade.php
@csrf

<div class="row">
    <div class="form-group col-md-6 {{ $errors->has('user_id') ? 'has-error' : '' }}">
        <label for="user_id">Asigne un usuario para que conduzca este carro</label>
        <select class="form-control select2-users " style="width: 100%;" name="user_id" required>
            <option value="" selected>Asigne un usuario para que conduzca este carrro</option>
            @forelse ($users as $user)
                <option value="{{ $user->id }}" {{ (collect(old('user_id'))->contains($user->id)) ? 'selected':'' }}>{{ $user->name }}</option>
            @empty
                <option value="">No hay usuarios</option>                
            @endforelse
        </select>
        @if ($errors->has('user_id'))
            <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('user_id') }}</strong>
            </span>
        @endif
    </div>
    <div class="col-md-6"></div>
    <div class="form-group col-md-6">
        <label for="car_brand">Marca del carro</label>
        <input class="form-control {{ $errors->has('car_brand') ? 'is-invalid' : '' }}" type="text" name="car_brand" value="{{ old('car_brand') }}" autofocus>
        @if ($errors->has('car_brand'))
            <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('car_brand') }}</strong>
            </span>
        @endif
    </div>
    <div class="form-group col-md-6">
        <label for="car_model">Modelo del carro</label>
        <input class="form-control {{ $errors->has('car_model') ? 'is-invalid' : '' }}" type="text" name="car_model" value="{{ old('car_model') }}">
        @if ($errors->has('car_model'))
            <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('car_model') }}</strong>
            </span>
        @endif
    </div>
    <div class="form-group col-md-6">
        <label for="car_plate">Placa del carro</label>
        <input class="form-control {{ $errors->has('car_plate') ? 'is-invalid' : '' }}" type="text" name="car_plate" value="{{ old('car_plate') }}">
        @if ($errors->has('car_plate'))
        <span class="invalid-feedback" role="alert">
            <strong>{{ $errors->first('car_plate') }}</strong>
        </span>
        @endif
    </div>        
    <div class="form-group col-md-6">
        <label for="car_seats">Número de asientos del carro</label>
        <input class="form-control {{ $errors->has('car_seats') ? 'is-invalid' : '' }}" type="number" name="car_seats" value="{{ old('car_seats') }}" min="1" max="50">
        @if ($errors->has('car_seats'))
            <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('car_seats') }}</strong>
            </span>
        @endif
    </div>    

    <div class="col-md-12">
            <button type="submit" class="btn btn-outline-success float-left">Terminar <i class="fas fa-check"></i></button>
            <a href="{{ route('cars.index') }}" class="btn btn-outline-secondary float-right">Regresar <i class="fas fa-arrow-alt-circle-left"></i></a>                
    </div>
</div>

resources/views/admin/cars/partials/create_car_modal.blade.php
<div id="ajaxModel" class="modal fade in" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modelHeading"></h5>
                
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="carForm" name="carForm">                           
                    <div class="row">                    
                        <div class="form-group col-md-12 ">
                            <label for="user_id">Asigne un usuario para que conduzca este carro</label>
                            <select id="user_id" class="form-control select2-users " style="width: 100%;" name="user_id" autofocus required>                                 
                            </select>                            
                                <span id="error-user_id" class="invalid-feedback" role="alert">                                    
                                </span>                            
                        </div>
                        <div class="form-group col-md-6">
                            <label for="car_brand">Marca del carro</label>
                            <input id="car_brand" class="form-control " type="text" name="car_brand" value="{{ old('car_brand') }}" required>                            
                                <span id="error-car_brand" class="invalid-feedback" role="alert">                                    
                                </span>                            
                        </div>
                        <div class="form-group col-md-6">
                            <label for="car_model">Modelo del carro</label>
                            <input id="car_model" class="form-control " type="number" name="car_model" value="{{ old('car_model') }}" min="1900" max="2020">                            
                                <span id="error-car_model" class="invalid-feedback" role="alert">                                    
                                </span>                            
                        </div>
                        <div class="form-group col-md-6">
                            <label for="car_plate">Placa del carro</label>
                            <input id="car_plate" class="form-control " type="text" name="car_plate" value="{{ old('car_plate') }}">                            
                                <span id="error-car_plate" class="invalid-feedback" role="alert">                                
                                </span>                            
                        </div>        
                        <div class="form-group col-md-6">
                            <label for="car_seats">Número de asientos del carro</label>
                            <input id="car_seats" class="form-control " type="number" name="car_seats" value="{{ old('car_seats') }}" min="1" max="50">                            
                                <span id="error-car_seats" class="invalid-feedback" role="alert">                                    
                                </span>                            
                        </div>
                        <div class="col-md-12">
                            <hr>                            
                            <input type="submit" class="btn btn-success" id="saveBtn" value="create">
                            <button type="button" class="btn btn-default waves-effect float-right" data-dismiss="modal">Cancelar</button>
                        </div>      
                    </div>
                </form>
            </div>            
        </div>
        <!-- /.modal-content -->
    </div>
</div>

@push('custom-scripts')    

    {{-- custom scripts --}}

@endpush

resources/views/admin/cars/partials/deleteModal.blade.php
<div class="modal fade" id="deleteCar-{{ $car->id }}">
    <div class="modal-dialog">
        <div class="modal-content bg-danger">
            <div class="modal-header">
                <h4 class="modal-title">¿Deseas eliminar este carro?</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <strong>¿Estas seguro de querer eliminarlo, recuerda que hay usuarios asociados a este carro?</strong>
            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-outline-light" data-dismiss="modal">Cancelar</button>
                <form action="{{ route('cars.destroy', $car) }}" method="post">
                    @csrf @method('DELETE')
                    <button type="submit" class="btn btn-outline-light">Si, eliminar</button>
                </form>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

resources/views/admin/cars/partials/editForm.blade.php
@csrf @method('PUT')

<div class="row">
    <div class="form-group col-md-6 {{ $errors->has('user_id') ? 'has-error' : '' }}">
        <label for="user_id">Asigne un usuario para que conduzca este carro</label>
        <select class="form-control select2-users " style="width: 100%;" name="user_id" required>
            <option value="">Asigne un usuario para que conduzca este carrro</option>
            <option value="{{ $car->User->id }}" selected>{{ $car->User->name }}</option>
            @forelse ($users as $user)
                <option value="{{ $user->id }}" {{ (collect(old('user_id'))->contains($user->id)) ? 'selected':'' }}>{{ $user->name }}</option>
            @empty
                <option value="">No hay usuarios</option>                
            @endforelse
        </select>
        @if ($errors->has('user_id'))
            <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('user_id') }}</strong>
            </span>
        @endif
    </div>
    <div class="col-md-6"></div>
    <div class="form-group col-md-6">
        <label for="car_brand">Marca del carro</label>
        <input class="form-control {{ $errors->has('car_brand') ? 'is-invalid' : '' }}" type="text" name="car_brand" value="{{ old('car_brand', $car->car_brand) }}" autofocus>
        @if ($errors->has('car_brand'))
            <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('car_brand') }}</strong>
            </span>
        @endif
    </div>
    <div class="form-group col-md-6">
        <label for="car_model">Modelo del carro</label>
        <input class="form-control {{ $errors->has('car_model') ? 'is-invalid' : '' }}" type="text" name="car_model" value="{{ old('car_model', $car->car_model) }}">
        @if ($errors->has('car_model'))
            <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('car_model') }}</strong>
            </span>
        @endif
    </div>
    <div class="form-group col-md-6">
        <label for="car_plate">Placa del carro</label>
        <input class="form-control {{ $errors->has('car_plate') ? 'is-invalid' : '' }}" type="text" name="car_plate" value="{{ old('car_plate', $car->car_plate) }}">
        @if ($errors->has('car_plate'))
        <span class="invalid-feedback" role="alert">
            <strong>{{ $errors->first('car_plate') }}</strong>
        </span>
        @endif
    </div>        
    <div class="form-group col-md-6">
        <label for="car_seats">Número de asientos del carro</label>
        <input class="form-control {{ $errors->has('car_seats') ? 'is-invalid' : '' }}" type="number" name="car_seats" value="{{ old('car_seats', $car->car_seats) }}" min="1" max="50">
        @if ($errors->has('car_seats'))
            <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('car_seats') }}</strong>
            </span>
        @endif
    </div>    

    <div class="col-md-12">
            <button type="submit" class="btn btn-outline-success float-left">Terminar <i class="fas fa-check"></i></button>
            <a href="{{ route('cars.index') }}" class="btn btn-outline-secondary float-right">Regresar <i class="fas fa-arrow-alt-circle-left"></i></a>                
    </div>
</div>

resources/views/admin/cars/partials/edit_car_modal.blade.php
<div id="editCar" class="modal fade in" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="edit-modelHeading"></h5>
                
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="carEditForm" name="carEditForm">                                
                    <div class="row">
                        <div class="form-group col-md-12 ">
                            <label for="user_id">Asigne un usuario para que conduzca este carro</label>
                            <select id="edit_user_id" class="form-control select2-users " style="width: 100%;" name="user_id" autofocus required>
                                <option value="" selected>Asigne un usuario para que conduzca este carrro</option>
                            </select>                     
                                <span id="error_edit_user_id" class="invalid-feedback" role="alert">                                    
                                </span>                            
                        </div>
                        <div class="form-group col-md-6">
                            <label for="car_brand">Marca del carro</label>
                            <input id="edit_car_brand" class="form-control " type="text" name="car_brand" value="{{ old('car_brand') }}" required>                            
                                <span id="error_edit_car_brand" class="invalid-feedback" role="alert">                                    
                                </span>                            
                        </div>
                        <div class="form-group col-md-6">
                            <label for="car_model">Modelo del carro</label>
                            <input id="edit_car_model" class="form-control " type="number" name="car_model" value="{{ old('car_model') }}" min="1900" max="2020">                            
                                <span id="error_edit_car_model" class="invalid-feedback" role="alert">                                    
                                </span>                            
                        </div>
                        <div class="form-group col-md-6">
                            <label for="car_plate">Placa del carro</label>
                            <input id="edit_car_plate" class="form-control " type="text" name="car_plate" value="{{ old('car_plate') }}">                            
                                <span id="error_edit_car_plate" class="invalid-feedback" role="alert">                                
                                </span>                            
                        </div>        
                        <div class="form-group col-md-6">
                            <label for="car_seats">Número de asientos del carro</label>
                            <input id="edit_car_seats" class="form-control " type="number" name="car_seats" value="{{ old('car_seats') }}" min="1" max="50">                            
                                <span id="error_edit_car_seats" class="invalid-feedback" role="alert">                                    
                                </span>                            
                        </div>                        
                        <div class="col-md-12">                            
                            <input type="submit" class="btn btn-success" id="saveEditBtn" value="edit">
                            <button type="button" class="btn btn-default waves-effect float-right" data-dismiss="modal">Cancelar</button>
                        </div>      
                    </div>
                </form>
            </div>            
        </div>
        <!-- /.modal-content -->
    </div>
</div>

@push('custom-scripts')    

   {{-- custom scripts --}}

@endpush

resources/views/admin/cars/partials/view_car_modal.blade.php
<div id="viewCar" class="modal fade in" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="view-modelHeading"></h5>
                
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">                                
                <div class="row">
                    <div class="col-md-6">
                        <h3>Marca del carro:</h3>
                        <div class="col-md-11 offset-1">
                            <strong id="view-car_brand"></strong>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <h3>Modelo del carro:</h3>
                        <div class="col-md-11 offset-1">
                            <strong id="view-car_model"></strong>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <h3>Placa del carro:</h3>
                        <div class="col-md-11 offset-1">
                            {{-- <strong id="member_since" >{{ $user->created_at->toFormattedDateString() }}</strong> --}}
                            <strong id="view-car_plate" ></strong>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <h3>Numero de asientos del carro:</h3>
                        <div class="col-md-11 offset-1">
                            {{-- <strong id="member_since" >{{ $user->created_at->toFormattedDateString() }}</strong> --}}
                            <strong id="view-car_seats" ></strong>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <h3>Usuario que maneja este carro:</h3>
                        <div id="car_user_relation" class="col-md-11 offset-1">
                                                        
                        </div>
                    </div>
                    <div class="col-md-12">
                        <hr>
                        <button type="button" class="btn btn-default waves-effect float-right" data-dismiss="modal">Cerrar</button>
                    </div>
                </div>

            </div>            
        </div>
        <!-- /.modal-content -->
    </div>
</div>

@push('custom-scripts')    

   {{-- custom scripts --}}

@endpush