routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
  if (auth::user()) {
    return view('admin.dashboard');
  }
    return view('auth.login');
});

Auth::routes();

Route::group([
    'prefix' => 'admin',
    'middleware' => 'auth'],
  function(){
    Route::view('inicio', 'admin.dashboard')->name('admin.dashboard');
    Route::resource('users', 'UserController');
    Route::resource('cars', 'CarController');

    Route::post('saveDataAccess', 'SaveDataAccessController@saveDataAccess')->name('save.data');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    // Mutators

        // Setters

            public function setPasswordAttribute($password)
            {
                $this->attributes['password'] = bcrypt($password);
            }

            public function setNameAttribute($name)
            {
                $this->attributes['name'] = ucwords($name);
            }

        // Getters

            

    // Relationships

    public function Cars()
    {
        return $this->hasMany(Car::class);
    }

    public function Accesses()
    {
        return $this->hasMany(UserAccess::class);
    }

    // Methods

    

}

app/Http/Controllers/Api/UserController.php
<?php

namespace App\Http\Controllers\Api;

use App\User;
use Illuminate\Http\Request;
use App\Events\UserWasCreated;
use App\Http\Requests\UserRequest;
use App\Http\Controllers\Controller;
use App\Http\Requests\UserUpdateRequest;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return datatables()
                ->eloquent(User::query())                
                ->addColumn('action', 'admin.users.partials.actions')
                ->rawColumns(['action'])
                ->toJson();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {
        $password = str_random(8);

        $user = User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => $password
        ]);

        UserWasCreated::dispatch($user, $password);

        $response = [
            'success'   => 'Se ha creado un usuario exitosamente',
            'codigo'  => '200',
            'user' => $user
        ];

        return $response;
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        $response = [
            'user' => $user,
            'user_cars_relation' => $user->Cars,
            'code' => 200,
        ];

        return $response;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(UserUpdateRequest $request, User $user)
    {
        $user->update($request->validated());

        $response = [
            'success'   => 'Se ha actualizado el usuario exitosamente',
            'codigo'  => '200',
            'user' => $user
        ];

        return $response;

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        if($user === auth()->user()->id){
            $response = [
                'error'   => 'No te puedes eliminar a ti mismo',                
            ];

            return $response;
        } else {
            $user->delete(); 

            $response = [
                'success'   => 'Se ha eliminado el usuario exitosamente',
                'codigo'  => '200',
            ];
            
            return $response;
        }
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use App\Events\UserWasCreated;
use App\Http\Requests\UserRequest;
use App\Http\Requests\UserUpdateRequest;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view('admin.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {        

        $password = str_random(8);

        $user = User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => $password
        ]);

        UserWasCreated::dispatch($user, $password);

        return redirect()->route('users.index')->with('info', 'Se ha creado un usuario exitosamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('admin.users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        // return view('admin.users.edit', compact('user'));

        return $user;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(UserUpdateRequest $request, User $user)
    {
        $user->update($request->validated());

        return redirect()->route('users.index')->with('info', 'Se ha actualizado el usuario exitosamente');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        // if($user->id === auth()->user()->id){            

        //     return redirect()->back()->with('error', 'No te puedes eliminar a ti mismo');
        // } 
        
        // $user->delete(); 
                    
        // return redirect()->back()->with('info', 'Se ha eliminado el usuario exitosamente');                  

        if($user->id === auth()->user()->id){
            $response = [
                'error'   => 'No te puedes eliminar a ti mismo',                
            ];

            return $response;
        } else {
            $user->Cars()->delete();
            $user->delete();

            $response = [
                'success'   => 'Se ha eliminado el usuario exitosamente',
                'codigo'  => '200',
            ];
            
            return $response;
        }                
    }
}

resources/views/admin/users/create.blade.php
@extends('layouts.admin')

@push('custom-styles')
    <!-- SweetAlert2 -->
    <link rel="stylesheet" href="/adminlte/plugins/sweetalert2/sweetalert2.min.css">
@endpush

@section('header')
    <div class="col-sm-6">
        <h1 class="m-0 text-dark">Módulo Usuarios</h1>
    </div><!-- /.col -->
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}"><i class="nav-icon fas fa-tachometer-alt"></i> Admin</a></li>
        <li class="breadcrumb-item"><a href="{{ route('users.index') }}"><i class=" fas fa-users"></i> Mod - Usuarios</a></li>
        <li class="breadcrumb-item active">Crear Usuario</li>
        </ol>
    </div><!-- /.col -->
@endsection

@section('content')
    <div class="col-md-12">
        <section class="content">
            <!-- Default box -->
            <div class="card card-success card-outline">
            <div class="card-header">
                <h3 class="card-title float-left">Creación de usuario</h3>

                <a href="{{ route('users.index') }}" class="btn btn-outline-secondary float-right">Regresar <i class="fas fa-arrow-alt-circle-left"></i></a>                
            </div>
            <div class="card-body">
                <form action="{{ route('users.store') }}" method="post">
                    @include('admin.users.partials.createForm')
                </form>                
            </div>
            <!-- /.card-body -->
            {{-- <div class="card-footer">            
                
            </div> --}}
            <!-- /.card-footer-->
            </div>
            <!-- /.card -->  
        </section>
        <!-- /.content -->
    </div>
@endsection

@push('custom-scripts')
    <!-- SweetAlert2 -->
    <script src="/adminlte/plugins/sweetalert2/sweetalert2.min.js"></script>    
    @include('admin.partials.sweetAlert.error')
@endpush

resources/views/admin/users/edit.blade.php
@extends('layouts.admin')

@push('custom-styles')
    <!-- SweetAlert2 -->
    <link rel="stylesheet" href="/adminlte/plugins/sweetalert2/sweetalert2.min.css">
@endpush

@section('header')
    <div class="col-sm-6">
        <h1 class="m-0 text-dark">Módulo Usuarios</h1>
    </div><!-- /.col -->
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}"><i class="nav-icon fas fa-tachometer-alt"></i> Admin</a></li>
        <li class="breadcrumb-item"><a href="{{ route('users.index') }}"><i class=" fas fa-users"></i> Mod - Usuarios</a></li>
        <li class="breadcrumb-item active">Editar usuario - {{ $user->name }}</li>
        </ol>
    </div><!-- /.col -->
@endsection

@section('content')
    <div class="col-md-12">
        <section class="content">
            <!-- Default box -->
            <div class="card card-warning card-outline">
            <div class="card-header">
                <h3 class="card-title float-left">Edición de usuario</h3>

                <a href="{{ route('users.index') }}" class="btn btn-outline-secondary float-right">Regresar <i class="fas fa-arrow-alt-circle-left"></i></a>                
            </div>
            <div class="card-body">
                <form action="{{ route('users.update', $user) }}" method="post">
                    @include('admin.users.partials.editForm')
                </form>                
            </div>
            <!-- /.card-body -->
            {{-- <div class="card-footer">            
                
            </div> --}}
            <!-- /.card-footer-->
            </div>
            <!-- /.card -->  
        </section>
        <!-- /.content -->
    </div>
@endsection

@push('custom-scripts')
    <!-- SweetAlert2 -->
    <script src="/adminlte/plugins/sweetalert2/sweetalert2.min.js"></script>    
    @include('admin.partials.sweetAlert.error')
@endpush

resources/views/admin/users/show.blade.php
@extends('layouts.admin')

@push('custom-styles')
    
@endpush

@section('header')
    <div class="col-sm-6">
        <h1 class="m-0 text-dark">Módulo Usuarios</h1>
    </div><!-- /.col -->
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href=""><i class="nav-icon fas fa-tachometer-alt"></i> Admin</a></li>
        <li class="breadcrumb-item"><a href="{{ route('users.index') }}"><i class=" fas fa-users"></i> Mod - Usuarios</a></li>
        <li class="breadcrumb-item active">Usuario - {{ $user->name }}</li>
        </ol>
    </div><!-- /.col -->
@endsection

@section('content')
    <div class="col-md-12">
        <section class="content">
            <!-- Default box -->
            <div class="card card-primary card-outline">
            <div class="card-header">                
                <h3 class="card-title float-left">Visualización de usuario - {{ $user->id }}</h3>                
                <a class="btn btn-outline-success float-right" href="{{ route('users.edit', $user) }}">Editar usuario <i class="fas fa-user-edit"></i></a>
                    {{-- <button class="btn btn-success btn-outline" data-toggle="modal" data-target="#addBtn">Crear usuario <i class="fas fa-plus"></i></button> --}}
                    {{-- @include('admin.users.partials.create_user_modal') --}}                    
            </div>
            
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <h3>Email:</h3>
                        <div class="col-md-11 offset-1">
                            <strong>{{ $user->email }}</strong>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <h3>Miembro desde:</h3>
                        <div class="col-md-11 offset-1">
                            <strong>{{ $user->created_at->toFormattedDateString() }}</strong>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <h3>Carros que maneja este usuario:</h3>
                        <div class="col-md-11 offset-1">
                            @forelse ($user->Cars as $car)
                                <span><strong>Id carro: {{ $car->id }} - </strong></span><span><a href="{{ route('cars.show', $car) }}">{{ $car->car_brand }}</a></span><br>
                                @unless($loop->last)
                                    <hr>
                                @endunless
                            @empty
                                <div class="col-md-12 offset-1">
                                    <strong>No se registraron carros para este usuario. Si quieres registrar un nuevo carro has clic <a href="{{ route('cars.create') }}">aquí</a></strong>
                                </div>
                            @endforelse                            
                        </div>
                    </div>
                      
                </div>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">            
                <a href="{{ route('users.index') }}" class="btn btn-outline-secondary float-right">Regresar <i class="fas fa-arrow-alt-circle-left"></i></a>
            </div>
            <!-- /.card-footer-->
            </div>
            <!-- /.card -->  
        </section>
        <!-- /.content -->
    </div>
    
@endsection

@push('custom-scripts')    

@endpush